--- 
- name: main site file
  hosts: all

  gather_facts: No

  tasks:
    - debug:
        msg:
          ansible_ssh_user: "{{ ansible_ssh_user }}"
          hostvars__inventory_hostname: "{{ hostvars[inventory_hostname] }}"
...
