---
- name: Password-Store tests
  hosts: password_store

  vars:
    password_store_dir: "{{ lookup('env', 'PASSWORD_STORE_DIR') }}"

  pre_tasks:
    - debug:
        msg:
          ansible_fqdn: "{{ ansible_fqdn }}"
          hostvars__inventory_hostname: "{{ hostvars[inventory_hostname] }}"
          PASSWORD_STORE_DIR: "{{ password_store_dir }}"

  roles:
    - password_store
...
